# Generated by Django 6.0.3 on 2026-03-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthtokenToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
            ],
            options={
                'db_table': 'authtoken_token',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjektInflacjaMobileAktualnecenyproduktowwdanymsklepie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dokladna_nazwa_produktu', models.CharField(max_length=100)),
                ('cena_produktu', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cena_produktu_za_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producent', models.CharField(max_length=100)),
                ('opakowanie', models.CharField(max_length=100)),
                ('data_dodania', models.DateField()),
            ],
            options={
                'db_table': 'projekt_inflacja_mobile_aktualnecenyproduktowwdanymsklepie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjektInflacjaMobileCenacalegoposilku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cena_calego_posilku', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
                ('brakujace_ceny_produktu', models.TextField()),
            ],
            options={
                'db_table': 'projekt_inflacja_mobile_cenacalegoposilku',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjektInflacjaMobileDiety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dieta', models.CharField(max_length=50)),
                ('opis_diety', models.TextField()),
            ],
            options={
                'db_table': 'projekt_inflacja_mobile_diety',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjektInflacjaMobileHistoriacenproduktow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dokladna_nazwa_produktu', models.CharField(max_length=100)),
                ('cena_produktu', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cena_produktu_za_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producent', models.CharField(max_length=100)),
                ('opakowanie', models.CharField(max_length=100)),
                ('data_dodania', models.DateField()),
            ],
            options={
                'db_table': 'projekt_inflacja_mobile_historiacenproduktow',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjektInflacjaMobileKalorycznosc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kalorycznosc', models.CharField(max_length=20)),
                ('czysta_kalorycznosc', models.IntegerField()),
            ],
            options={
                'db_table': 'projekt_inflacja_mobile_kalorycznosc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjektInflacjaMobileKalorycznoscdiety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'projekt_inflacja_mobile_kalorycznoscdiety',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjektInflacjaMobileKategorieproduktow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_kategorii', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'projekt_inflacja_mobile_kategorieproduktow',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjektInflacjaMobileKolejnosckategoriiwsklepie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolejnosc', models.IntegerField()),
            ],
            options={
                'db_table': 'projekt_inflacja_mobile_kolejnosckategoriiwsklepie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjektInflacjaMobileListazakupowrodziny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_listy_zakupow', models.CharField(max_length=100, unique=True)),
                ('data_od', models.DateField()),
                ('data_do', models.DateField()),
            ],
            options={
                'db_table': 'projekt_inflacja_mobile_listazakupowrodziny',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjektInflacjaMobileMagazynwszystkichuzytkownikowrodziny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc_produktu', models.FloatField()),
            ],
            options={
                'db_table': 'projekt_inflacja_mobile_magazynwszystkichuzytkownikowrodziny',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjektInflacjaMobileMiarki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_miarki', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'projekt_inflacja_mobile_miarki',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjektInflacjaMobileMozliweocenyposilku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocena', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'projekt_inflacja_mobile_mozliweocenyposilku',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjektInflacjaMobileOcenaposilkuprzezuzytkownika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_oceny', models.DateField()),
            ],
            options={
                'db_table': 'projekt_inflacja_mobile_ocenaposilkuprzezuzytkownika',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjektInflacjaMobilePoraposilku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pora_posilku', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'projekt_inflacja_mobile_poraposilku',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjektInflacjaMobilePosilki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_posilku', models.CharField(max_length=100)),
                ('obraz_bitowy', models.TextField()),
                ('czy_wlasny', models.BooleanField()),
            ],
            options={
                'db_table': 'projekt_inflacja_mobile_posilki',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjektInflacjaMobilePosilkiwdiecie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kalorie', models.IntegerField()),
                ('bialko', models.IntegerField()),
                ('weglowodany', models.IntegerField()),
                ('tluszcze', models.IntegerField()),
                ('opis_posilku', models.TextField()),
                ('czas_przygotowania', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'projekt_inflacja_mobile_posilkiwdiecie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjektInflacjaMobileProdukty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_produktu', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'projekt_inflacja_mobile_produkty',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjektInflacjaMobileProduktynalisciezakupowrodziny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc_produktu_do_kupienia', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'projekt_inflacja_mobile_produktynalisciezakupowrodziny',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjektInflacjaMobileProduktyuproszczone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_produktu_uproszczonego', models.CharField(max_length=100)),
                ('kalorie', models.IntegerField()),
                ('bialko', models.IntegerField()),
                ('weglowodany', models.IntegerField()),
                ('tluszcze', models.IntegerField()),
                ('opis_produktu', models.TextField()),
            ],
            options={
                'db_table': 'projekt_inflacja_mobile_produktyuproszczone',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjektInflacjaMobileProduktywposilku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc_produktu', models.CharField(max_length=20)),
                ('czysta_ilosc_produktu', models.IntegerField()),
            ],
            options={
                'db_table': 'projekt_inflacja_mobile_produktywposilku',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjektInflacjaMobileRodziny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzina', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'projekt_inflacja_mobile_rodziny',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjektInflacjaMobileSklepy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_sklepu', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'projekt_inflacja_mobile_sklepy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjektInflacjaMobileUzytkownicywrodzinach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'projekt_inflacja_mobile_uzytkownicywrodzinach',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjektInflacjaMobileWszystkiemiarki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_miarki', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'projekt_inflacja_mobile_wszystkiemiarki',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjektInflacjaMobileZaplanowaneposilkirodziny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('czy_zjedzone', models.BooleanField()),
            ],
            options={
                'db_table': 'projekt_inflacja_mobile_zaplanowaneposilkirodziny',
                'managed': False,
            },
        ),
    ]
